# Generated by Django 5.1 on 2024-08-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
